"""
Personalized recommendations fully generated by Gemini 2.5 Flash.
Falls back to rule-based only if Gemini is unavailable.
"""
import json
from typing import List, Dict
from config import settings


def generate_recommendations(
    avg_score: float,
    attendance: int,
    weak_subjects: List[str],
    strong_subjects: List[str] = None,
    student_name: str = "",
    test_scores: List[float] = None,
) -> List[Dict]:
    # Try Gemini first
    if settings.GOOGLE_API_KEY:
        result = _gemini_recommendations(
            avg_score=avg_score,
            attendance=attendance,
            weak_subjects=weak_subjects,
            strong_subjects=strong_subjects or [],
            student_name=student_name,
            test_scores=test_scores or [],
        )
        if result:
            return result

    # Fallback: rule-based
    return _rule_based(avg_score, attendance, weak_subjects)


def _gemini_recommendations(avg_score, attendance, weak_subjects,
                             strong_subjects, student_name, test_scores) -> List[Dict]:
    try:
        from google import genai
        client = genai.Client(api_key=settings.GOOGLE_API_KEY)

        weak_str   = ", ".join(weak_subjects[:5]) if weak_subjects else "жоқ"
        strong_str = ", ".join(strong_subjects[:5]) if strong_subjects else "жоқ"
        scores_str = ", ".join([f"{s:.0f}%" for s in test_scores[-5:]]) if test_scores else "деректер жоқ"

        prompt = f"""Сіз — білім беру AI кеңесшісіз. Студентке жеке оқу ұсыныстарын жазыңыз.

Студент туралы деректер:
- Аты: {student_name or 'Студент'}
- Орташа тест балы: {avg_score:.1f}%
- Қатысу: {attendance}%
- Соңғы тест нәтижелері: {scores_str}
- Қиналатын пәндер: {weak_str}
- Жақсы пәндер: {strong_str}

3 нақты, жеке оқу кеңесін ҚАЗАҚ тілінде жазыңыз.
Әр кеңес студенттің нақты жағдайына сәйкес болсын — шаблон емес.
Қатысу төмен болса — сол жайлы, пән төмен болса — нақты сол пән жайлы кеңес беріңіз.

JSON массиві форматында қайтарыңыз:
[
  {{"title": "Қысқа тақырып (5-7 сөз)", "body": "2-3 сөйлем нақты кеңес"}},
  {{"title": "...", "body": "..."}},
  {{"title": "...", "body": "..."}}
]
Тек JSON массивін шығарыңыз."""

        response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)
        text = response.text.strip()
        if text.startswith("```"):
            text = text.split("```", 2)[1]
            if text.startswith("json"):
                text = text[4:]
        recs = json.loads(text.strip())
        if isinstance(recs, list) and recs:
            return [{"title": r.get("title", ""), "body": r.get("body", ""), "subject": None}
                    for r in recs[:3]]
    except Exception as e:
        print(f"[Recommendations] Gemini error: {e}")
    return []


def _rule_based(avg_score, attendance, weak_subjects) -> List[Dict]:
    recs = []
    for subject in weak_subjects[:2]:
        recs.append({
            "title": "Пәнді қайталаңыз",
            "body": f"{subject} пәні бойынша балыңыз төмен. Негізгі тақырыптарды қайталап шығыңыз.",
            "subject": subject,
        })
    if attendance < 80:
        recs.append({
            "title": "Қатысуды арттырыңыз",
            "body": f"Қатысу деңгейіңіз {attendance}%. Сабаққа тұрақты қатысу үлгерімге оң әсер етеді.",
            "subject": None,
        })
    if not recs:
        recs.append({
            "title": "Тұрақтылықты сақтаңыз",
            "body": "Оқу қарқыныңызды жалғастырыңыз. Тұрақтылық — үздік үлгерімнің кілті.",
            "subject": None,
        })
    return recs
