/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'inverse-primary': '#ffb4ac',
        surface: 'var(--color-surface)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant': 'var(--color-surface-container-highest)',
        'surface-tint': 'var(--color-primary)',
        background: 'var(--color-surface)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        secondary: '#546067',
        'secondary-container': '#d7e4ec',
        'secondary-fixed': '#d7e4ec',
        'secondary-fixed-dim': '#bbc8d0',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a666d',
        'on-secondary-fixed': '#111d23',
        'on-secondary-fixed-variant': '#3c494f',
        tertiary: '#006578',
        'tertiary-container': '#008097',
        'tertiary-fixed': '#afecff',
        'tertiary-fixed-dim': '#72d4ef',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f9fdff',
        'on-tertiary-fixed': '#001f27',
        'on-tertiary-fixed-variant': '#004e5d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 12px 40px rgba(25, 28, 29, 0.06)',
        card: '0 4px 20px rgba(0,0,0,0.02)',
        primary: '0 8px 24px rgba(183,19,26,0.2)',
      },
    },
  },
  plugins: [],
}
